services:
  init-check:
    image: alpine
    volumes:
      - ./check_initialized.sh:/check_initialized.sh
      - ./nginx:/nginx
    command: sh /check_initialized.sh

  comfyui:
    depends_on:
      init-check:
        condition: service_completed_successfully
    image: zeroclue/comfyui:ultra-slim-torch2.8.0-cu128
    volumes:
      - ./models:/workspace/ComfyUI/models
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  nginx:
    image: nginx:alpine
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - comfyui
